### ISSUE TITLE
RuntimeError when training

### ISSUE THREAD

**Issue by Br0kenSmi1e** [deepmodeling/CrystalFormer#6]
When running the training part of CrystalFormer following the README file, a ```RuntimeError``` is raised.
When running the command
```
python ./main.py --folder ./data/ --train_path YOUR_PATH/mp_20/train.csv --valid_path YOUR_PATH/mp_20/val.csv
```
the program prints
```
number of available cpu:  8
num_io_process should not exceed number of available cpu, reset to  8
```
and then shows an error.
Detailed error information is listed below:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/longli/pycode/CrystalFormer/CrystalFormer/main.py", line 93, in <module>
    train_data = GLXYZAW_from_file(args.train_path, args.atom_types, args.wyck_types, args.n_max, args.num_io_process)
  File "/Users/longli/pycode/CrystalFormer/CrystalFormer/crystalformer/src/utils.py", line 149, in GLXYZAW_from_file
    p = multiprocessing.Pool(num_workers)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/context.py", line 288, in _Popen
    return Popen(process_obj)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Users/longli/miniconda3/envs/crystalformer/lib/python3.10/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Comment by zdcao121** [comment]
You have to run your Pool inside the block `__main__:` if using the spawn in multiprocessing. We do not implement the `__main__` block in the `main.py` due to the default setting is fork on linux.
https://stackoverflow.com/questions/69229588/multiprocessing-module-error-if-name-main
